---
- block:

  - name: 'packages: install common packages'
    become: true
    apt:
      name:
        - build-essential
        - software-properties-common
        - git
        - golang
        - python3
        - python3-pip
        - python3-setuptools
        - virtualenv
      state: present
      update_cache: yes

  tags:
    - common
    - packages
