---
- block:

  - name: 'seclists: create directory'
    become: true
    file:
      path: /usr/share/wordlists/
      state: directory

  - name: 'seclists: clone repo'
    become: true
    git:
      accept_hostkey: yes
      clone: yes
      dest: /usr/share/wordlists/seclists
      repo: https://github.com/danielmiessler/SecLists.git

  tags:
    - wordlists
    - seclists