---
- block:

  - name: 'ffuf: clone repo'
    git:
      accept_hostkey: yes
      clone: yes
      dest: /tmp/ffuf
      repo: https://github.com/ffuf/ffuf.git

  - name: 'ffuf: go get'
    shell: '{{ shell }} -lc "/usr/bin/go get"'
    args:
      chdir: /tmp/ffuf

  - name: 'ffuf: go build'
    shell: '{{ shell }} -lc "/usr/bin/go build"'
    args:
      chdir: /tmp/ffuf

  - name: 'ffuf: create shortcut file'
    become: true
    copy:
      dest: '/usr/local/bin/ffuf'
      owner: root
      group: root
      mode: 0755
      content: |
        #!{{ shell }}
        {{ goPath }}/ffuf "$@"

  - name: 'ffuf: remove temp files'
    file:
      dest: /tmp/ffuf
      state: absent

  tags:
    - web
    - ffuf