---
- block:

  - name: 'ffuf: clone repo'
    git:
      accept_hostkey: yes
      clone: yes
      dest: /tmp/ffuf
      repo: https://github.com/ffuf/ffuf.git

  - name: 'ffuf: go get'
    shell: '{{ shell }} -lc "/usr/bin/go get"'
    args:
      chdir: /tmp/ffuf

  - name: 'ffuf: go build'
    shell: '{{ shell }} -lc "/usr/bin/go build"'
    args:
      chdir: /tmp/ffuf

  - name: 'ffuf: Update path'
    become: true
    vars:
      newPath: ~/go/bin
    lineinfile:
      dest: /etc/environment
      state: present
      regexp: '^(PATH=\")({{ newPath }}:)?((?(2).*?(?!(?:.\"))|.*?(?!(?:{{ newPath }}))))(:{{ newPath }})?((?(4).*|\"))'
      line: '\1\3:{{ newPath }}\5'
      backrefs: yes

  - name: 'ffuf: remove temp files'
    file:
      dest: /tmp/ffuf
      state: absent

  tags:
    - web
    - ffuf