---
- block:

  - name: 'nikto: install dependencies'
    become: true
    apt:
      name:
        - libnet-ssleay-perl
        - libwhisker2-perl
        - perl-openssl-defaults
      state: present
      update_cache: yes

  - name: 'nikto: clone repo'
    become: true
    git:
      accept_hostkey: yes
      clone: yes
      dest: '{{ programInstallDir }}/nikto'
      repo: https://github.com/sullo/nikto.git

  - name: 'nikto: create shortcut file'
    become: true
    copy:
      dest: '/usr/local/bin/nikto'
      owner: root
      group: root
      mode: 0755
      content: |
        #!{{ shell }}
        {{ programInstallDir }}/nikto/program/nikto.pl "$@"

  tags:
    - web
    - nikto
