---
- block:

  - name: 'WitnessMe: clone repo'
    become: true
    git:
      accept_hostkey: yes
      clone: yes
      dest: '{{ programInstallDir }}/witnessme'
      repo: https://github.com/byt3bl33d3r/WitnessMe.git

  - name: 'WitnessMe: install pipx dependency via pip'
    pip:
      name: pipx
      executable: /usr/bin/pip3
      extra_args: --user

  - name: 'WitnessMe: install'
    shell: '{{ shell }} -lc "~/.local/bin/pipx install witnessme"'

  - name: 'WitnessMe: Update path'
    become: true
    vars:
      newPath: ~/.local/bin
    lineinfile:
      dest: /etc/environment
      state: present
      regexp: '^(PATH=\")({{ newPath }}:)?((?(2).*?(?!(?:.\"))|.*?(?!(?:{{ newPath }}))))(:{{ newPath }})?((?(4).*|\"))'
      line: '\1\3:{{ newPath }}\5'
      backrefs: yes

  tags:
    - web
    - witnessme
