---
- block:

  - name: 'LinkFinder: clone repo'
    become: true
    git:
      accept_hostkey: yes
      clone: yes
      dest: '{{ programInstallDir }}/linkfinder'
      repo: https://github.com/GerbenJavado/LinkFinder.git

  - name: 'LinkFinder: remove venv directory'
    become: true
    file:
      path: '{{ programInstallDir }}/linkfinder/.venv'
      state: absent

  - name: 'LinkFinder: create venv'
    become: true
    shell: '{{ shell }} -lc "virtualenv -p python3 {{ programInstallDir }}/linkfinder/.venv"'

  - name: 'Linkfinder: install requirements'
    become: true
    pip:
      requirements: '{{ programInstallDir }}/linkfinder/requirements.txt'
      state: present
      virtualenv: '{{ programInstallDir }}/linkfinder/.venv'

  - name: 'LinkFinder: create shortcut'
    become: true
    copy:
      dest: '/usr/local/bin/linkfinder'
      owner: root
      group: root
      mode: 0755
      content: |
        #!{{ shell }}
        source {{ programInstallDir }}/linkfinder/.venv/bin/activate
        python3 {{ programInstallDir }}/linkfinder/linkfinder.py "$@"
        deactivate

  tags:
    - web
    - linkfinder
